# Generated by Django 5.0.4 on 2024-04-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240426_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='event_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
