# Generated by Django 5.0.4 on 2024-04-29 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_name_booking_event_name_booking_email_and_more'),
    ]

    operations = [
    ]
