# Generated by Django 5.0.4 on 2024-05-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_eventdetail_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetail',
            name='cost',
        ),
    ]
