# Generated by Django 5.0.4 on 2024-05-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_feedback_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
