# Generated by Django 5.0.4 on 2024-05-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='details',
            field=models.CharField(max_length=1000),
        ),
    ]
